local_costmap:
   global_frame: map
   robot_base_frame: robot_footprint  
   update_frequency: 2.0
   publish_frequency: 2.0
   transform_tolerance: 0.25
   width: 2.0
   height: 2.0
   resolution: 0.05
   static_map: false
   rolling_window: true
   inflation_radius: 0.2

